library(ggplot2)
data = read.table(file = snakemake@input[[1]], header=T, stringsAsFactors=F, skip = 4)
p = ggplot(data, aes(x=BIN, y = VALUE))
p = p + geom_bar(stat = 'identity')
p = p + labs(title=paste('Length of SMART adapter trimmed in\n', snakemake@wildcards$sample), x='Length', y='Counts')
p = p + scale_x_continuous(breaks = c(data$BIN), labels = factor(data$BIN))
p = p + scale_y_continuous(labels = scales::scientific)
ggsave(plot = p, snakemake@output$pdf, height = 6, width = 8)