library(ggplot2)
library(ggpubr)
options(warn=-1)
data = read.table(file = snakemake@input[[1]], header=T, stringsAsFactors=F, skip = 4)
p = ggplot(data, aes(x=BIN, y = VALUE))
p = p + geom_bar(stat = 'identity')
p = p + labs(title=paste('Length of SMART adapter trimmed in\n', snakemake@wildcards$sample), x='Length', y='Counts') 
p = p + theme_pubr()
p = p + scale_x_continuous(breaks = c(data$BIN), labels = factor(data$BIN))
ggsave(plot = p, snakemake@output$pdf, height = 6, width = 8)
ggsave(plot = p, snakemake@output$png, height = 6, width = 8)