library(ggplot2)
library(ggpubr)
data = read.table(file = snakemake@input[[1]], header=T, stringsAsFactors=F, skip = 4)
p = ggplot(data, aes(x=BIN, y = VALUE))
p = p + geom_bar(stat = 'identity')
p = p + labs(title=paste('Length of polyA trimmed in\n', snakemake@wildcards$sample), x='Length', y='Counts')
p = p + theme_pubr()
p = p +  geom_smooth()
p = p + scale_x_continuous(breaks = seq(0,data$BIN[length(data$BIN)], 10), labels = seq(6,data$BIN[length(data$BIN)]+6, 10))
p = p + scale_y_continuous(labels = scales::scientific)
ggsave(plot = p, snakemake@output$pdf, height = 6, width = 8)
