library(ggplot2)
library(ggpubr)
data = read.table(file = snakemake@input[[1]], header=T, stringsAsFactors=F)
data$presence=rep('kept', nrow(data))
ids = which(snakemake@params$num_below_quality < data$num_failed_bases)
data$presence[ids] = 'dropped'
dropped = sum(data$num_barcodes[ids])
p = ggplot(data, aes(x=num_failed_bases, y=num_barcodes, fill = presence))
p = p + geom_bar(stat = 'identity')
p = p + ggtitle(paste('Number of CELL barcode bases under', snakemake@params$min_quality,'quality in\n', snakemake@wildcards$sample,'\nTagged', format(dropped, big.mark = '\''),'Reads'))
p = p + labs(x='Num of failed bases', y='Counts')
p = p + theme_pubr(legend = 'bottom')
p = p + scale_x_continuous(breaks = c(data$num_failed_bases), labels = factor(data$num_failed_bases))
p = p + geom_vline(aes(xintercept = snakemake@params$num_below_quality + 0.5), color = 'red')
ggsave(plot = p, snakemake@output$pdf, height = 4, width = 6)
ggsave(plot = p, snakemake@output$png, height = 4, width = 6)
